[all:vars]
ansible_user=vagrant
ansible_password=vagrant
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
ansible_winrm_scheme=http

[dcs]
dc01-prod ansible_host=127.0.0.1 ansible_port=59851
dc02-dev-tree ansible_host=127.0.0.1 ansible_port=59852

[members]
ws01-prod ansible_host=127.0.0.1 ansible_port=59853
srv01-apps ansible_host=127.0.0.1 ansible_port=59854

[corp_domain]
dc01-prod
ws01-prod

[dev_domain]
dc02-dev-tree
srv01-apps
